# ============================================================================
# n8n Production Stack - OrbStack Single-Node Configuration
# ============================================================================
version: '3.8'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  n8n_webhook_data:
    driver: local
  n8n_mcp_data:
    driver: local
  n8n_worker_data:
    driver: local
  letsencrypt:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  n8n-network:
    driver: overlay
    attachable: true

services:
  postgres:
    image: postgres:16-alpine
    deploy:
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TIMEZONE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - n8n-network

  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory ${REDIS_MAXMEMORY:-512mb}
      --maxmemory-policy ${REDIS_MAXMEMORY_POLICY:-allkeys-lru}
      --requirepass ${REDIS_PASSWORD}
      --port ${REDIS_PORT:-6379}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '${REDIS_PORT:-6379}', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - n8n-network

  traefik:
    image: traefik:v3.5.3
    deploy:
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    command:
      # Global
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      # API
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=true"
      # Logging
      - "--log.level=DEBUG"
      - "--log.format=common"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8080"
      # HTTP Redirect
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Docker Provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=n8n-network"
      - "--providers.docker.watch=true"
      # Let's Encrypt
      - "--certificatesresolvers.letsencrypt.acme.email=pesnik@outlook.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:8080/ping']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - n8n-network

  n8n-webhook:
    image: docker.n8n.io/n8nio/n8n:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=n8n-network"
        # Main Router - catches everything
        - "traefik.http.routers.n8n-main.rule=Host(`n8n.agentshq.net`)"
        - "traefik.http.routers.n8n-main.entrypoints=websecure"
        - "traefik.http.routers.n8n-main.tls.certresolver=letsencrypt"
        - "traefik.http.routers.n8n-main.service=n8n-webhook"
        # API Router
        - "traefik.http.routers.n8n-api.rule=Host(`n8n.agentshq.net`) && PathPrefix(`/api`)"
        - "traefik.http.routers.n8n-api.entrypoints=websecure"
        - "traefik.http.routers.n8n-api.tls.certresolver=letsencrypt"
        - "traefik.http.routers.n8n-api.service=n8n-webhook"
        # Webhook Router  
        - "traefik.http.routers.n8n-webhooks.rule=Host(`n8n.agentshq.net`) && PathPrefix(`/webhook`)"
        - "traefik.http.routers.n8n-webhooks.entrypoints=websecure"
        - "traefik.http.routers.n8n-webhooks.tls.certresolver=letsencrypt"
        - "traefik.http.routers.n8n-webhooks.service=n8n-webhook"
        # Service definition
        - "traefik.http.services.n8n-webhook.loadbalancer.server.port=5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_POOL_SIZE: 4
      
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_BULL_REDIS_DB: 0
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      QUEUE_HEALTH_CHECK_ACTIVE: "true"
      
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false"
      
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: "https://${N8N_HOST}/"
      N8N_EDITOR_BASE_URL: "https://${N8N_HOST}/"
      
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_ON_PROGRESS: "true"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: 336
      
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      
      N8N_PAYLOAD_SIZE_MAX: 16
      N8N_METRICS: "true"
      
      LOG_LEVEL: info
      LOG_OUTPUT: console
    volumes:
      - n8n_webhook_data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - n8n-network

  n8n-mcp:
    image: docker.n8n.io/n8nio/n8n:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=n8n-network"
        - "traefik.http.routers.n8n-mcp.rule=Host(`n8n.agentshq.net`) && PathPrefix(`/mcp`)"
        - "traefik.http.routers.n8n-mcp.entrypoints=websecure"
        - "traefik.http.routers.n8n-mcp.tls.certresolver=letsencrypt"
        - "traefik.http.routers.n8n-mcp.service=n8n-mcp"
        - "traefik.http.routers.n8n-mcp.priority=100"
        - "traefik.http.services.n8n-mcp.loadbalancer.server.port=5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_POOL_SIZE: 2
      
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_BULL_REDIS_DB: 0
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false"
      
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: "https://${N8N_HOST}/"
      N8N_EDITOR_BASE_URL: "https://${N8N_HOST}/"
      
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      
      LOG_LEVEL: info
      LOG_OUTPUT: console
    volumes:
      - n8n_mcp_data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - n8n-network

  n8n-worker:
    image: docker.n8n.io/n8nio/n8n:latest
    deploy:
      replicas: 2
    entrypoint: ["sh", "-c"]
    command: |
      n8n worker --concurrency=$${N8N_WORKER_CONCURRENCY:-10}
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_POOL_SIZE: 4
      
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_BULL_REDIS_DB: 0
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false"
      
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      
      N8N_PAYLOAD_SIZE_MAX: 16
      
      LOG_LEVEL: info
      LOG_OUTPUT: console

      N8N_RUNNERS_ENABLED: "true"
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_GIT_NODE_DISABLE_BARE_REPOS: "true"
    volumes:
      - n8n_worker_data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'n8n worker' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - n8n-network

  prometheus:
    image: prom/prometheus:latest
    deploy:
      replicas: 1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=45d"
      - "--web.listen-address=:9090"
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - n8n-network

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=n8n-network"
        - "traefik.http.routers.grafana.rule=Host(`grafana.agentshq.net`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: "https://grafana.${N8N_HOST}"
      TZ: ${TIMEZONE}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - n8n-network

  alertmanager:
    image: prom/alertmanager:latest
    deploy:
      replicas: 1
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"
    volumes:
      - alertmanager_data:/alertmanager
      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - n8n-network
