# ============================================================================
# n8n Production Stack - MCP-Compatible Architecture
# Based on: https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-langchain.mcptrigger/
# Architecture: Separated webhook handler, dedicated MCP replica, worker pool
# ============================================================================
version: '3.8'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  n8n_webhook_data:
    driver: local
  n8n_mcp_data:
    driver: local
  n8n_worker_data:
    driver: local
  traefik_data:
    driver: local
  letsencrypt:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  n8n-network:
    external: true
    name: n8n-network

services:
  # ============================================================================
  # STATE LAYER: PostgreSQL (Manager Node Only)
  # ============================================================================
  postgres:
    image: postgres:16-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: >-
        -c max_connections=100
        -c shared_buffers=256MB
        -c effective_cache_size=1GB
        -c work_mem=16MB
      TZ: ${TIMEZONE}
      # Enable pg_stat_statements for monitoring
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  # ============================================================================
  # QUEUE LAYER: Redis (Manager Node Only)
  # ============================================================================
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory ${REDIS_MAXMEMORY:-512mb}
      --maxmemory-policy ${REDIS_MAXMEMORY_POLICY:-allkeys-lru}
      --requirepass ${REDIS_PASSWORD}
      --port ${REDIS_PORT:-6379}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '${REDIS_PORT:-6379}', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  # ============================================================================
  # INGRESS LAYER: Traefik with mkcert certificates (Manager Node Only)
  # ============================================================================
  traefik:
    image: traefik:v3.5.3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./config/traefik/certs:/etc/traefik/certs:ro
      - traefik_data:/etc/traefik/acme
    environment:
      TZ: ${TIMEZONE}
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  # ============================================================================
  # APPLICATION: n8n WEBHOOK Handler (Manager Node Only)
  # Handles: Regular webhooks, UI, API calls (NOT MCP)
  # ============================================================================
  n8n-webhook:
    image: docker.n8n.io/n8nio/n8n:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        
        # Main n8n route
        - "traefik.http.routers.n8n.rule=Host(`n8n.agentshq.net`)"
        # - "traefik.http.routers.n8n.rule=Host(`${N8N_HOST}`)"
        - "traefik.http.routers.n8n.entrypoints=websecure"
        - "traefik.http.routers.n8n.priority=10"
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"
        # - "traefik.http.routers.n8n.middlewares=n8n-headers@file,compress@file"
        - "traefik.http.routers.n8n.middlewares=n8n-headers,compress"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    environment:
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_POOL_SIZE: 4
      
      # Queue Mode
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_BULL_REDIS_DB: 0
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      QUEUE_HEALTH_CHECK_ACTIVE: "true"
      
      # Security
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      
      # URLs - CRITICAL for webhooks
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: "https://${N8N_HOST}/"
      N8N_EDITOR_BASE_URL: "https://${N8N_HOST}/"
      
      # Execution
      EXECUTIONS_DATA_SAVE_ON_SUCCESS: all
      EXECUTIONS_DATA_SAVE_ON_ERROR: all
      EXECUTIONS_DATA_SAVE_ON_PROGRESS: "true"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: 336  # 14 days
      
      # Timezone
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      
      # Performance
      N8N_PAYLOAD_SIZE_MAX: 16
      N8N_METRICS: "true"
      
      # Logging
      LOG_LEVEL: info
      LOG_OUTPUT: console
    volumes:
      - n8n_webhook_data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

  # ============================================================================
  # APPLICATION: n8n MCP DEDICATED REPLICA (Manager Node Only)
  # CRITICAL: Single replica for MCP SSE/streamable HTTP persistence
  # Routes: /mcp/* only
  # ============================================================================
  n8n-mcp:
    image: docker.n8n.io/n8nio/n8n:latest
    deploy:
      replicas: 1  # MUST BE 1 - DO NOT SCALE
      labels:
        - "traefik.enable=true"
        
        # MCP route - HIGHEST PRIORITY
        # - "traefik.http.routers.n8n-mcp.rule=Host(`${N8N_HOST}`) && PathPrefix(`/mcp`)"
        - "traefik.http.routers.n8n-mcp.rule=Host(`n8n.agentshq.net`) && PathPrefix(`/mcp`)"
        - "traefik.http.routers.n8n-mcp.entrypoints=websecure"
        - "traefik.http.routers.n8n-mcp.priority=100"
        - "traefik.http.services.n8n-mcp.loadbalancer.server.port=5678"
        # - "traefik.http.routers.n8n-mcp.middlewares=mcp-sse@file"
        - "traefik.http.routers.n8n-mcp.middlewares=mcp-sse"
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    environment:
      # Database (same as webhook)
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_POOL_SIZE: 2
      
      # Queue Mode
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_BULL_REDIS_DB: 0
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # Security
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      
      # URLs
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: "https://${N8N_HOST}/"
      N8N_EDITOR_BASE_URL: "https://${N8N_HOST}/"
      
      # Timezone
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      
      # Logging
      LOG_LEVEL: info
      LOG_OUTPUT: console
    volumes:
      - n8n_mcp_data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

  # ============================================================================
  # WORKERS: n8n Queue Processors (Worker Nodes - Global Mode)
  # ============================================================================
  n8n-worker:
    image: docker.n8n.io/n8nio/n8n:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    entrypoint: ["/bin/sh", "-c"]
    command: |
      n8n worker --concurrency=$${N8N_WORKER_CONCURRENCY:-10}
    environment:
      # Database
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_POOL_SIZE: 4
      
      # Queue Mode
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT:-6379}
      QUEUE_BULL_REDIS_DB: 0
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      
      # Security
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      
      # Timezone
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      
      # Performance
      N8N_PAYLOAD_SIZE_MAX: 16
      
      # Logging
      LOG_LEVEL: info
      LOG_OUTPUT: console
    volumes:
      - n8n_worker_data:/home/node/.n8n
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'n8n worker' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

  # ============================================================================
  # OBSERVABILITY: Prometheus, Grafana, AlertManager
  # (Keeping your existing configs - they're fine)
  # ============================================================================
  prometheus:
    image: prom/prometheus:latest
    deploy:
      replicas: 1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=45d"
      - "--storage.tsdb.retention.size=45GB"
      - "--web.listen-address=:9090"
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`grafana.${N8N_HOST}`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SERVER_ROOT_URL: "https://grafana.${N8N_HOST}"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
      TZ: ${TIMEZONE}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

  alertmanager:
    image: prom/alertmanager:latest
    deploy:
      replicas: 1
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"
    volumes:
      - alertmanager_data:/alertmanager
      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    networks:
      - n8n-network
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "3"
